Repository openshift/pipelines-docs, pull requests merged in 2019-09, with the labels that each got.

#12 Bump dependencies
  package-lock.json
  package.json
Labels: size/XL

#13 Developer preview note
  modules/ROOT/pages/index.adoc
Labels: Peer Review Done, size/S

#10 [WIP] SRVKP-303: Examples for Tekton Concepts
  modules/ROOT/nav.adoc
  modules/ROOT/pages/assembly_understanding-openshift-pipelines.adoc
  modules/ROOT/pages/con-pipeline-resource-types.adoc
  modules/ROOT/pages/con_pipeline-cluster-resource.adoc
  modules/ROOT/pages/con_pipeline-git-resources.adoc
  modules/ROOT/pages/con_pipeline-image-resources.adoc
  modules/ROOT/pages/con_pipeline-pull-request-resources.adoc
  modules/ROOT/pages/con_pipeline-task-syntax.adoc
  modules/ROOT/pages/con_pipeline-task.adoc
  modules/ROOT/pages/con_pipelines-concepts.adoc
Labels: SME Review Needed, do-not-merge/work-in-progress, size/L

#16 Create code_of_conduct.md
  code_of_conduct.md
Labels: size/M

#14 Edits to Openshift Pipelines Docs Landing Page
  docs/docs/index.html
Labels: size/S

#15 [WIP] added-crc-procedure
  modules/ROOT/pages/proc_deploying-an-application-to-openshift.adoc
Labels: do-not-merge/work-in-progress, size/S
