Repository openshift/pipelines-docs, pull requests merged in 2019-08, with the labels that each got.

#2 Adding cli commands
  modules/ROOT/pages/proc_assembling-a-pipeline.adoc
  modules/ROOT/pages/proc_checking-pipeline-and-application-status.adoc
  modules/ROOT/pages/proc_defining-and-creating-pipeline-tasks.adoc
  modules/ROOT/pages/proc_defining-and-creating-pipelineresources.adoc
  modules/ROOT/pages/proc_deploying-an-application-to-openshift.adoc
  modules/ROOT/pages/proc_installing-pipelines-operator.adoc
  modules/ROOT/pages/proc_triggering-and-running-a-pipeline.adoc
Labels: size/L

#4 Installing, upgrading, uninstalling
  modules/ROOT/pages/assembly_installing-pipelines.adoc
  modules/ROOT/pages/proc_installing-pipelines-operator.adoc
  modules/ROOT/pages/proc_uninstalling-pipelines-operator.adoc
Labels: size/S

#3 Cli reference
  modules/ROOT/nav.adoc
  modules/ROOT/pages/assembly_cli_reference.adoc
  modules/ROOT/pages/proc_installing_cli.adoc
  modules/ROOT/pages/ref_cli_reference.adoc
Labels: size/L

#7 update nav.adoc
  modules/ROOT/nav.adoc
Labels: size/XS

#6 Fixed formatting errors in Installing CLI section
  modules/ROOT/pages/proc_checking-pipeline-and-application-status.adoc
  modules/ROOT/pages/proc_installing_cli.adoc
Labels: size/S

#11 Adding Cluster admin privileges note to install
  modules/ROOT/pages/proc_installing-pipelines-operator.adoc
Labels: Peer Review Needed, size/XS
