Repository openshift/pipelines-docs, pull requests merged in 2019-12, with the labels that each got.

#76 Fix broken link to install tekton CLI
  docs/docs/0.7/proc_deploying-an-application-to-openshift.html
Labels: size/XS

#85 Update release notes version
  modules/ROOT/pages/release_notes_0.8.adoc
Labels: size/XS

#88 RN for 0.8
  modules/ROOT/pages/release_notes_0.8.adoc
Labels: size/M

#87 changes according to tutorial
  modules/ROOT/assets/images/application-deployed.png
  modules/ROOT/pages/proc_assembling-a-pipeline.adoc
  modules/ROOT/pages/proc_defining-and-creating-pipeline-tasks.adoc
  modules/ROOT/pages/proc_defining-and-creating-pipelineresources.adoc
  modules/ROOT/pages/proc_deploying-an-application-to-openshift.adoc
  modules/ROOT/pages/proc_triggering-and-running-a-pipeline.adoc
Labels: size/XXL
