Repository openshift/pipelines-docs, pull requests merged in 2019-10, with the labels that each got.

#19 0.5 branch
  README.md
Labels: size/S

#18 update install, upgrade, and uninstall procedures
  modules/ROOT/pages/proc_deploying-an-application-to-openshift.adoc
  modules/ROOT/pages/proc_installing-pipelines-operator.adoc
  modules/ROOT/pages/proc_triggering-and-running-a-pipeline.adoc
  modules/ROOT/pages/proc_uninstalling-pipelines-operator.adoc
Labels: size/M

#21 0.7 release notes
  modules/ROOT/pages/release_notes_0.7.adoc
Labels: size/M

#27 update antora configuration
  antora.yml
Labels: size/XS

#25 update antora configuration
  antora.yml
Labels: size/XS

#29 minor edits
  modules/ROOT/pages/proc_defining-and-creating-pipeline-tasks.adoc
  modules/ROOT/pages/proc_defining-and-creating-pipelineresources.adoc
  modules/ROOT/pages/proc_uninstalling-pipelines-operator.adoc
  modules/ROOT/pages/ref_cli_reference.adoc
Labels: size/S

#32 Updated links in CLI ref to v0.4.0
  modules/ROOT/pages/ref_cli_reference.adoc
Labels: size/M

#35 move dev-preview notice under heading fixes "untitled" in page title
  modules/ROOT/pages/index.adoc
Labels: size/XS

#37 move dev-preview notice under heading
  modules/ROOT/pages/index.adoc
Labels: size/XS

#36 move dev-preview notice under heading
  modules/ROOT/pages/index.adoc
Labels: size/XS

#38 Wed Oct 23 16:18:42 CEST 2019
  docs/docs/0.5/index.html
  docs/docs/0.7/assembly_cli_reference.html
  docs/docs/0.7/assembly_installing-pipelines.html
  docs/docs/0.7/assembly_using-pipelines.html
  docs/docs/0.7/index.html
  docs/docs/0.7/proc_defining-and-creating-pipeline-tasks.html
  docs/docs/0.7/proc_defining-and-creating-pipelineresources.html
  docs/docs/0.7/proc_uninstalling-pipelines-operator.html
  docs/docs/0.7/ref_cli_reference.html
  docs/sitemap.xml
Labels: size/L

#39 odc pipelines docs
  modules/ROOT/assets/images/pipeline_list.png
  modules/ROOT/assets/images/pipeline_overview.png
  modules/ROOT/assets/images/pipeline_run.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/proc_assembling-a-pipeline.adoc
  modules/ROOT/pages/proc_defining-and-creating-pipeline-tasks.adoc
  modules/ROOT/pages/proc_defining-and-creating-pipelineresources.adoc
  modules/ROOT/pages/proc_deploying-an-application-to-openshift.adoc
  modules/ROOT/pages/proc_installing_cli.adoc
  modules/ROOT/pages/proc_triggering-and-running-a-pipeline.adoc
  modules/ROOT/pages/proc_working_with_pipelines_using _developer_perspective.adoc
  modules/ROOT/pages/release_notes_0.7.adoc
Labels: size/M

#41 windows commands for installing tkn
  modules/ROOT/pages/proc_installing_cli.adoc
Labels: size/S

#48 fix antora version reference
  antora.yml
Labels: size/XS

#50 update antora configuration (#27)
  antora.yml
Labels: size/XS

#51 fix-404-index-by-redirect
  docs/docs/index.html
Labels: size/XS

#52 add+fix index.html pipelines take 2
  docs/docs/index.html
Labels: size/XS
