Repository openshift/pipelines-docs, pull requests merged in 2020-03, with the labels that each got.

#103 Link Updates for the current release 0.10
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/proc_deploying-an-application-to-openshift.adoc
  modules/ROOT/pages/proc_installing-pipelines-operator-in-web-console.adoc
Labels: size/S

#104 Pipelines on developer perspective
  modules/ROOT/assets/images/pipeline_import_flow.png
  modules/ROOT/assets/images/pipeline_list.png
  modules/ROOT/assets/images/pipeline_overview.png
  modules/ROOT/assets/images/pipeline_run.png
  modules/ROOT/assets/images/pipelines_details.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/assembly_installing-pipelines.adoc
  modules/ROOT/pages/assembly_working-with-pipelines-using-the-developer-perspective.adoc
  modules/ROOT/pages/proc_creating-applications-with-cicd-pipelines.adoc
  modules/ROOT/pages/proc_interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/ROOT/pages/proc_working-with-pipelines-using-developer-perspective.adoc
Labels: size/L

#102 0.10 Release Notes
  modules/ROOT/nav.adoc
  modules/ROOT/pages/release_notes.adoc
  modules/ROOT/pages/release_notes_0.8.adoc
Labels: size/L

#110 Flow+img changes
  modules/ROOT/assets/images/application-deployed.png
  modules/ROOT/assets/images/deployment_complete.png
  modules/ROOT/assets/images/pipeline_details.png
  modules/ROOT/assets/images/pipeline_topology.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/assembly_creating-applications-with-cicd-pipelines.adoc
  modules/ROOT/pages/assembly_using-pipelines.adoc
  modules/ROOT/pages/proc_checking-pipeline-and-application-status.adoc
  modules/ROOT/pages/proc_creating-applications-with-cicd-pipelines.adoc
  modules/ROOT/pages/proc_creating-project-and-checking-pipeline-service-account.adoc
  modules/ROOT/pages/proc_deploying-an-application-to-openshift.adoc
  modules/ROOT/pages/proc_interacting-with-pipelines-using-the-developer-perspective.adoc
Labels: size/XXL

#111 publishing docs
  docs/0.10.5/_images/application-deployed.png
  docs/0.10.5/_images/deployment_complete.png
  docs/0.10.5/_images/pipeline_details.png
  docs/0.10.5/_images/pipeline_topology.png
  docs/0.10.5/assembly_cli-reference.html
  docs/0.10.5/assembly_creating-applications-with-cicd-pipelines.html
  docs/0.10.5/assembly_installing-pipelines.html
  docs/0.10.5/assembly_working-with-pipelines-using-the-developer-perspective.html
  docs/0.10.5/con-pipeline-resource-types.html
  docs/0.10.5/con_pipeline-cluster-resource.html
  docs/0.10.5/con_pipeline-git-resources.html
  docs/0.10.5/con_pipeline-image-resources.html
  docs/0.10.5/con_pipeline-pull-request-resources.html
  docs/0.10.5/con_pipeline-task.html
  docs/0.10.5/con_pipelines-concepts.html
  docs/0.10.5/index.html
  docs/0.10.5/proc_assembling-a-pipeline.html
  docs/0.10.5/proc_checking-pipeline-and-application-status.html
  docs/0.10.5/proc_creating-applications-with-cicd-pipelines.html
  docs/0.10.5/proc_creating-project-and-checking-pipeline-service-account.html
  docs/0.10.5/proc_defining-and-creating-pipeline-tasks.html
  docs/0.10.5/proc_defining-and-creating-pipelineresources.html
  docs/0.10.5/proc_installing-cli.html
  docs/0.10.5/proc_installing-pipelines-operator-in-web-console.html
  docs/0.10.5/proc_installing-pipelines-operator-using-the-cli.html
  docs/0.10.5/proc_interacting-with-pipelines-using-the-developer-perspective.html
  docs/0.10.5/proc_triggering-and-running-a-pipeline.html
  docs/0.10.5/proc_uninstalling-pipelines-operator.html
  docs/0.10.5/ref_cli-reference.html
  docs/0.10.5/release_notes.html
  docs/0.5/assembly_using-pipelines.html
  docs/0.5/proc_deploying-an-application-to-openshift.html
  docs/0.7/assembly_using-pipelines.html
  docs/0.7/proc_deploying-an-application-to-openshift.html
  docs/0.8/assembly_using-pipelines.html
  docs/0.8/proc_deploying-an-application-to-openshift.html
  sitemap.xml
Labels: size/XXL

#108 Updates to CLI Reference - RHDEVDOCS-1521
  modules/ROOT/nav.adoc
  modules/ROOT/pages/assembly_cli-reference.adoc
  modules/ROOT/pages/op-tkn-clustertask-management.adoc
  modules/ROOT/pages/op-tkn-condition-management.adoc
  modules/ROOT/pages/op-tkn-pipeline-management.adoc
  modules/ROOT/pages/op-tkn-pipeline-resource-management.adoc
  modules/ROOT/pages/op-tkn-pipeline-run.adoc
  modules/ROOT/pages/op-tkn-reference.adoc
  modules/ROOT/pages/op-tkn-task-management.adoc
  modules/ROOT/pages/op-tkn-task-run.adoc
  modules/ROOT/pages/op-tkn-trigger-management.adoc
  modules/ROOT/pages/op-tkn-utility-commands.adoc
  modules/ROOT/pages/ref_cli-reference.adoc
Labels: size/XL

#113 Changes made for RHDEVDOCS-1688
  modules/ROOT/pages/con-pipeline-resource-types.adoc
  modules/ROOT/pages/op-installing_pipelines.adoc
Labels: size/M

#112 Edit Changes for Concept Topics
  modules/ROOT/pages/con_pipelines-concepts.adoc
  modules/ROOT/pages/index.adoc
Labels: size/M
