Repository openshift/pipelines-docs, pull requests merged in 2020-02, with the labels that each got.

#92 Minor Edits
  modules/ROOT/pages/index.adoc
Labels: size/XS

#95 WIP: update README.md Fri 17 Jan 2020 04:32:26 PM CET
  README.md
  local-site.yml
Labels: do-not-merge/work-in-progress, size/M

#98 updating contributing guidelines and the site yaml for new branch
  README.md
  contributing/con_contributing-documentation.md
  site.yml
Labels: size/L

#99 formatting
  contributing/con_contributing-documentation.md
Labels: size/M

#97 Minor Changes in Installation Procedure
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/proc_deploying-an-application-to-openshift.adoc
  modules/ROOT/pages/proc_installing-pipelines-operator-in-web-console.adoc
  modules/ROOT/pages/proc_installing-pipelines-operator-using-the-cli.adoc
Labels: size/M

#100 Pipeline Tutorial Updates
  modules/ROOT/pages/assembly_using-pipelines.adoc
  modules/ROOT/pages/proc_assembling-a-pipeline.adoc
  modules/ROOT/pages/proc_checking-pipeline-and-application-status.adoc
  modules/ROOT/pages/proc_defining-and-creating-pipeline-tasks.adoc
  modules/ROOT/pages/proc_defining-and-creating-pipelineresources.adoc
  modules/ROOT/pages/proc_deploying-an-application-to-openshift.adoc
  modules/ROOT/pages/proc_triggering-and-running-a-pipeline.adoc
Labels: size/L
